version: '3.0'

x-postgres-vars: &postgres-vars
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


services:

  postgre:
    image: postgres
    restart: always
    environment:
      <<: *postgres-vars
    networks:
      - shared-net

  adminer:
    image: adminer
    ports:
      - 8088:8080
    networks:
      - shared-net

  rabbit:
    image: bitnami/rabbitmq:3.11.11
    container_name: rabbit
    hostname: rabbit
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - shared-net



networks:
  shared-net:
    external: True